version: '2'
services:
    keygeneration-app:
        image: keygeneration
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://keygeneration-postgresql:5432/KeyGeneration
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    keygeneration-postgresql:
        extends:
            file: postgresql.yml
            service: keygeneration-postgresql
